sudo: required

services:
  - docker

install:
  - sudo apt-get update -q
  - sudo apt-get install -y qemu-utils btrfs-tools

before_script:
  - sudo qemu-img create /var/lib/docker/btrfs.img 10G
  - sudo mkfs.btrfs /var/lib/docker/btrfs.img
  - sudo service docker stop
  - sudo mkdir -p /var/lib/buttervolume
  - sudo mount -o loop /var/lib/docker/btrfs.img /var/lib/buttervolume
  - sudo mkdir -p /var/lib/buttervolume/{volumes,snapshots,received}
  - sudo service docker start
  - docker build -t anybox/buttervolume docker/

script:
  - docker run -it --rm --privileged -v /var/lib/buttervolume:/var/lib/buttervolume -v "$PWD":/usr/src/buttervolume -w /usr/src/buttervolume -e SSH_PORT=113 anybox/buttervolume test
